title: Aniket's Blog
description: A blog to help manage my computer science journey from August 2023 to June 2024
show_downloads: true
baseurl: "/caveman"
google_analytics:
theme: jekyll-theme-cayman
